---
title: "Lab Notebook: February 2019"
output: html_notebook
---
#Goals: Mar 25 - 29
1. Authorship paper:
    + cont read Lancet Women's issue
    + Review gender rep story/figures

1. ~~Spring strategic plan~~

1. ~~SWC Meeting - Tues @ 9am~~

1. Lab meeting - Tues @ 2pm

1. ASM blog
  + ~~submit S. epi post~~
  + revise S. epi post
  
#2019/03/25

**- Spring strategic plan**

**- Prep for Thursday talk**

title: Falling with Style: A Millenial's Career Path

central message: career paths aren't linear, be open to opportunity & willing to take risks

outline:

**- Finished & submitted S. epi post**

#Goals: Mar 18 -22
1. Authorship paper:
    + cont read Lancet Women's issue
    + Revise gender rep figures
    + ~~Double-check how I handled hypens in names~~
    + ~~Generate de-identified summary dataset~~

1. Dept DEI
    + ~~Present at DEI meeting - Mon @noon~~

1. Geographical survey - Mia
    + Finish geographic bias
    
1. ASM blog -- Monday
    + ~~outline/research "S.epi"~~
    + write draft of "S.epi"
    
1. Code review -- Tuesday
    + ~~Prep code review~~
    + ~~Present at lab meeting~~

#2019/03/21

**- Begum's specific aims**

Review & make suggestions.

**- Authorship paper**

Finished function to randomize the day portion of dates & added the calculation for the interval between decision date & ready.for.production.date to the parse xml functions.

Compiled all scripts from xml parsing project into a single pipeline that used the api as a commandline argument & submitted it to flux. The result should be a completely de-identified dataset in a few weeks.

#2019/03/20

**- Authorship paper**

Double-checked how I handled hyphens & realized that I didn't address either periods or hyphens in names. Also realized that a `case_when` statement wasn't working if there were multiple issues within a single name entry. Redesigned `replace_special` as a series of `if_else` statements. Need to re-run the genderize analysis again.

Working on creating a function to randomize the day portion of the dates to further anonymize the dataset.

Also need to calculate the days between decision date & ready.for.production.date.

**- Prepped for lab meeting next week**

#2019/03/19

**- Authorship paper**

Worked on new summary figures

**- Nellie Tran Seminar**

**- Prepped & sent out code review**

**- Lab meeting**

Code review. Meeting w. Pat on Friday morning. Look at map2/pmap?

Going to work w. Begum on her specific aims & proposal.

#2019/03/18

**- DEI meeting**

**- ASM blog post** 

Switch topics to skin microbiota & immunity.

Pull relevant papers & start taking notes & making the outline.

#Goals: Mar 11 - Mar 15
1. Authorship paper:
    + cont read Lancet Women's issue
    + ~~Revise gender rep figures~~
    + ~~Update representation intro/disc/methods~~

1. Dept DEI
    + ~~Skype w. Josie @ 10~~
    + ~~Present at faculty meeting - Tues @noon~~

1. Geographical survey - Mia
    + Finish geographic bias
    
1. ASM blog
    + ~~outline/research "origins of life"~~
    + ~~comments on paleomicro post~~
    
1. Prep code review for next week

1. DEI certificate
    + ~~Microaggressions - Thurs,@ 3pm~~
    + ~~“Liberating Structures” - Fri, @ noon~~

#2019/03/15

**- Authorship paper** 

Finally finished the alluvial plot(s)!!

**- Mia**

Checked in on progress & provided another round of feedback for her ASM capstone application.

**- DEI certificate**

Attended "Liberating Structures" & submitted reflection forms for both it and yesterday's session. I'm all done now!!

#2019/03/14

**- Authorship paper**

Organized data into format for alluvial plot.

Revised Representation intro, discussion & method outlines.

**- Seminar**

**- DEI certificate**

Attended a session/panel on microaggressions.

#2019/03/13

**- Authorship paper**

Worked on revising gender rep figures. Decided to try to make alluvial plots to track flow of indivivduals from jr author -> sr author -> potential rev -> reviewer -> editor.
    
#2019/03/12

**- Lab meeting**

**- ASM blog**

Suggestions to paleomicrobiology post.

Work on "origins of life" post research.

**- Dept DEI**

Update graphs & go over slides w. Josie.

Present to faculty!

#2019/03/11

**- Dept DEI**

Update slides for Josie.

**- Misc**

Weekly report

#Goals: Mar 4 - Mar 8
1. Authorship paper:
    + cont read Lancet Women's issue
    + ~~Finish gender rep figures~~

1. Monthly journals report
    + test monthly reports pipeline?
    + update figures from new dataset

1. Geographical survey - Mia
    + Spring Break
    
1. Microbe Talk
    + ~~Clean up slides~~
    
1. SWC
    + ~~Update Lessons per Thursday Feedback~~
    
1. ASM blog
    + outline/research "origins of life"

#2019/03/08

**- Meeting w. Josie**

Tweak a couple of graphs. Send resources for representation matters. 

**- Authorship paper**

Figured out how to print all of my png files using `Rmd`. Going to try to story board the gender section of the representation paper. What do I have, what do I need, what is most interesting/helpful?

Came up with several questions/suggestions for presenting the data to see the differences more clearly:
1. is the increased publication proportion relative to submission proportional for M vs W?
1. overlay subs & pubs over time or totals
1. what is the distribution of subs & pubs by individuals by gender --> boxplot? i.e., what gender is more likely to have multiple papers -- looking at last/coress
1. Look at %women overtime by journal (& %M, %U)
1. plot unique F/L/C/M % or total unique auth OT -- are we retaining w?
1. what is n of senior editors?
1. plot prop of potential rev vs actual rev over time -- how does that compare to first/last auth
1. are m/w handeling equivalent shares of papers? -- unique editor - % of total papers?


#2019/03/07

**- Meeting w. Speaker**

Steven Finkel gave me a great idea! Apparently, NIH/NSF collect race/ethnicity data of fundees -- use acknowledgements section to get awards & link back to race data!

**- Sukhmani's defense**

**- Seminar**

**- Authorship paper**

Wrote scripts for box plots of reviewer frequency by gender & editor assignment by gender.

#2019/03/06

**- Authorship paper**

Finish writing functions & scripts to generate **45** customized plots of the unique, published & submitted authors for each type for both all ASM journals combined and separate.

Also cleaned up & finished scripts to generate/save similar plots for editors & reviewers. Something's odd about the "senior editor" grouping... need to check that out.

#2019/03/05

**- Lab meeting**

**- Authorship paper**

FINALLY finished my function w. 3 nested if statements & an internal mapping function!!!! -- it came down to an issue of quotes. Go figure.

#2018/03/04

**- ASM blog**

outline/research "origins of life"

**- Microbe talk**

Clean up slides

**- Update Git Lessons**

Add analogy for .gitignore files & update instructions to self/setup sections.

**- Misc**

AAAS & ASM trip reimbursements. 

Weekly report. 

List.files example to Emily

#Goals: Mar 4 - Mar 8
1. Authorship paper:
    + cont read Lancet Women's issue

1. Monthly journals report
    + ~~continue working through Dashboard book~~
    + ~~stream-line highwire data retrieval~~

1. Geographical survey - Mia
    + Work on representation figures
    + Send CV to Paul?
    + ~~Meeting - Mon @11~~

1. ASM HQ - Tuesday
    + ~~Quarterly Journals Staff mtg - 1pm~~
    + ~~Microbe talk mtg - 2pm~~
    + ~~Slides for microbe talk?~~
    
1. SWC - Thursday
    + ~~Teach Git - afternoon~~
    + ~~Update Git Lesson plan~~
    
1. ASM blog
    + outline/research "origins of life"
    

#2019/03/01

**- SWC Python**

Anaconda is a collection of data science "packages" written in python.
+ Add strings together with "+" or multiply with "*"
+ "Type" has two characteristics: the data & the methods that can be applied to the data
+ autofill in python "name." gives list of actions that can be performed on that variable
+ Move order of cells by clicking on cell & using up/down arrows in the menu
+ Hit esc to toggle out to "command mode" then A to insert a cell above the cell you're in
+ delete a cell w. esc - X
+ Juypter supports markdown
+ Python can be used with either Python, R or Julia kernals
+ Rodeo - RStudio for Python
+ headers are important, glossaries are even better

```{r}
library(reticulate)
use_virtualenv("r-reticulate")
py_available(TRUE)
```
```{python}
name = "fred rogers"
len(name)
```

**- Emails**

Deborah about API needs for cites/usage.

Elle about followup survey for reviewers

Amy K about ethics & DEI/bias

Amy C about BOD meeting


**- goal for next week? concept map of publishing talk...**