---
title: "Lab Notebook: May 2019"
output: html_notebook
---
#Goals: May 27 - 31
1. Gender bias paper:
    + ~~review all figures~~
    + generate 2nd line figures
    + Ouline & Figures to Pat -- F

1. Microbe
    + microbiology myths -- wait
    + Slides & practice for Microbe Talk

1. Monthly journals report -- waiting for feedback
    
1. ASM blog -- wait

1. Geographic Rep
    + make next line figures
    + review/tweak all figures
    + Outline & Figures to Pat -- F
    
#2019/05/29

**- Gender bias**



**- Meeting w. Harry**

#2019/05/28

**- Monthly Report Feedback**

Pat:
  + editor/month tables sorting alphabetical instead of numeric - might need to `as.numeric` the month columns &/or check out the NAs being generated (na vs NA), that might also be throwing things
  + need to work out the data.table error
  + try color with the journal submissions plot
  
Melissa:
  + 
  
Tried to troubleshoot key authentication w. ejpress
  
**- Microbe**

Revise work plan & send to Melissa.

**- Gender bias**

 + Look through all firstline images to find & refine the story. 
 + Make notes to improve for 2nd line images. 
 + Further investigae EJP decisions & withdrawn papers.
 
**- Lab meeting**

#Goals: May 13 - 17
1. Gender bias paper:
    + ~~work on finishing previous figures~~
    + ~~script new set of figures~~
    + ~~get regression dataset to Begum~~

1. Microbe
    + microbiology myths -- wait
    + ~~3yr work plan -- Pat, Thurs @ 2:30~~

1. SWC 
    + Git Revamp - hold until after Microbe
    
1. Monthly journals report
    + ~~pull new data~~
    + ~~citation/usage stats~~
    + ~~final touches on monthly report~~
    + send to Pat/Melissa
    
1. ASM blog
    + ~~revisions on origin blog~~

1. Geographic Rep
    + ~~go over second line figures~~
    + make next line figures

#2019/05/26

**- Monthly Journals Report**

Restarted `run_monthly_reports.R` job. Ran all reports

**- Gender Bias**

Finished generating rough figures & print.

#2019/05/24

**- Monthly Journals Report**

Still working on pipeline. [Found a piece of data that I need but wasn't in the parsing function used. Added it to the code & re-ran `report_parse.R`.]x2

I think I made all of the needed tweaks in the report & started a job overnight to run all of the `run_report` script.

**- Microbe**

Finished draft of 3yr workplan & sent to Pat.

#2019/05/23

**- Monthly Journals Report**

Worked on finishing touches to the workflow & got a dataset ready to run through the report scripts.

**- ASM blog**

Finished suggestions to the blog.

**- Gender bias**



**- Meeting w. Pat**

Talked about the 3yr work plan. He gave me some suggestions of ideas for future research and language to use. I need to give them a draft for comments.

#2019/05/22

**- Gender Rep**

Go through 2nd line figures. Have to figure out the best way to show all of the different regions.

**- Gender Bias**

Made additional changes to the dataset for Begum.

**- ASM blog**

Made a few changes to the blog post.

#2019/05/21

**- Gender bias**

Work on figuring out what is happening to reviewer ids. -- incorrect joining during deidentification step. Fixed, which meant I had to re-do how I load in reviewer data for analysis and drop all ".y" from the end of column names. -- fixed for both gender_analysis & representation projects. 

Made the process of binning US institutions faster by spliting and joining.

Made final changes to script to generate the regression data for Begum & ran.

Sent new df to Begum.

**- Lab Meeting**

Learned about R documentation!!!

#2019/05/20

**- Misc**

Microbe schedule planning & weekly report.

**- Gender bias**

Get regression data for Begum:
  + Revisit binning institutions. Final categories == R1, R2, medical/insitutes, government, industry, & low research
  + Calculate prop of F authors on each manuscript.
  + Get average reviewer rank. -- found something weird in the reviewer data -- reviewer.random.id seems to be assigned based on manuscript & not individual. Need to look into this.
  + Gather historical jif, max jif, and foundation years, to calculate a "percieved JIF".
      + Percieved JIF = Avg JIF (2010-2017) + Max JIF + # Years since founded
      
**-Monthly Report**

Pulled 3 year data dump from ejp & emailed joel about getting my public key set up.

Need to get citation/usage stats from impact vizor.

#Goals: May 13 - 17
1. Gender bias paper:
    + work on finishing previous figures
    + script new set of figures
    + start results outline/figures

1. Microbe
    + microbiology myths -- wait
    + ~~meeting @ 11:30~~

1. SWC 
    + ~~Git Revamp - Git D lesson~~
    
1. Monthly journals report
    + ~~arrange data transfers~~
    
1. ASM blog
    + ~~finish origin blog~~
    + ~~revise blog~~
    + ~~submit to Julie~~
    + ~~comments on ? blog~~

1. Publishing in Dev Countries
    + submit questionaire to IRB
    + get suggestions from international rep -- waiting
    
1. Geographic Rep
    + go over second line figures w. Mia
    + suggest next line figures
    + revise outline
    
1. ~~Journal club~~

#2019/05/17

**- Microbe**

Phone call w. journals crew.

**- Gender bias**

Finish binning research institutions.

**- Geographic rep**

Meet with Mia & save images to date. Need to look over them on Monday.

#2019/05/16

**- Bystander Intervention Training (ASM)**

**- Gender bias**

Work on binning institution types.

**- Misc**

Start 3 year work plan.

#2019/05/15

**- Gender bias**

Work on binning institution types.

**- Misc**

Finished clarifying/arranging data transfers from ejp.

Emailed about SEA Change.

Emailed Amy Chang.

Emailed Rebecca about Diversify M&I.

**- Invited Speaker Paper**

Met with Josie to discuss & plan a paper about the invited speaker dataset.

**- ASM blog**

Finished origin blog post, went through revisions with Begum, & submitted to Julie.

#2019/05/14

**- Lab meeting**

Prep for journal club.

**- ASM blog**

Work on blog & check in w. Begum.

Suggestions for Julie

#2019/05/13

**- Misc**

Weekly report & goals.

**- ASM blog**

Suggestions for blog post on immune amnesia & measles.

Work on origin of life blog

**- SWC**

Work on Git lesson D revamp.

#Goals: May 6 - 10
1. Gender bias paper:
    + ~~script fig 5~~
    + start results outline/figures

1. Microbe
    + ~~finish journals concept map~~
    + ~~update journals slides~~
    + ~~microbiology myths~~

1. SWC 
    + ~~Git Revamp - Git C lesson~~
    
1. Monthly journals report
    + ?
    
1. ASM blog
    + ~~work on origin blog~~

1. Publishing in Dev Countries
    + submit questionaire to IRB
    + get suggestions from international rep -- waiting
    
1. Geographic Rep
    + ~~go over figures w. Mia~~
    + ~~suggest next line figures~~
    + revise outline

#2019/05/10

**- ASM blog**

Worked on origin of life blog

**- Microbe**

Worked on microbial myths

#2019/05/09

**- ASM blog**

Work on origin blog post.

**- Microbe**

Work on microbiology myths.

#2019/05/08

**- Microbe**

Finished draft of journals concept map & send updated slides.

**- Gender bias**

Flux job failed again b/c of the editors dataset. Used an interactive job to finish the pipeline. Clean up flux folders. Share updated data w. Mia

Missing CVI & mBio for articles between 1 & 12 mo published w. view stats

Missing mBio for articles between 24 & 48 mo published w. cite stats

Figures that need work:

time_at_journ - revisit w. days.pending calculated - done
rev_accept_gender - need potential reviewer dataset - started coding

Need to bin institutions, US vs non-US researchers, # of authors, reviewer recomendations, JIF of previous year, "percieved impact" (composite IF with number added to account for age)

**- Lit review**

Sift through alert emails for relevant papers.

#2019/05/07

**- Lab meeting**

**- SWC**

Git Revamp - Git C lesson

**- Journal club**

Find & share paper for journal club next week. 

**- Microbe**

Worked on slides.

#2019/05/06

**- Microbe**

Worked on slides for journals talk.

**- Geographic Rep**

Went over figures with Mia & made suggestions for next round.


#Goals: April 29 - May 3
1. Gender bias paper:
    + ~~finish scripting fig 4 - logistical regressions dataset~~
    + ~~finish scripting fig 3~~
    + script fig 5
    
1. ~~Meet w. Pat -- Mon @ 1pm~~

1. Microbe
    + ~~journals concept map~~
    + update journals slides
    + ~~microbiology myths~~
    + ~arrange meetings to discuss data (Hazel & international rep)~~

1. SWC 
    + ~~Git Revamp - Git B lesson~~
    
1. Estimated JIF
    + ~~develop strategy~~
    + learn crossRef API -- not needed ATM

1. Monthly journals report
    + ?
    
1. ASM blog
    + ~~work on origin blog (Friday)~~

1. Publishing in Dev Countries
    + submit questionaire to IRB
    + get suggestions from international rep -- waiting
    
1. ~~Geographic figures w. Mia - Mon @ 2pm~~

#2019/05/03

**- Gender bias**

Re-script logistic regression dataset to include days, cite data, num revisions/authors/reviewers, etc. Now just waiting for the flux job to finish so that I can also include days.pending

Was going to start scripting figure 5, but I'm waiting on the flux job to finish.

Worked on trying to find reviewer score systems.

**- ASM blog**

Work on intro & outline to origin of life blog.

**- Microbe**

Work on journals concept map

#2019/05/02

**- Microbe**

Worked on microbial myths doc.

Worked on journals concept map.

#2019/05/01

**- Josie Teaching Demo**

**- Gender bias**

Worked on finishing scripting figure 3. Added citation & usage data & started a couple of correlation plots. 

**- Geographic figures**

Sorted out the issues Mia was having with her figures. 
  + Rstudio kept crashing b/c it was trying to use an entire df to name a figure, swapped that out for a name.
  + Some figures looked jagged overtime b/c they needed to be facetted by journal