---
title: "Lab Notebook: October 2018"
output: html_document
---
#Goals: Oct 29 - Nov 2
1. Authorship paper:
    + Work on bugs in webscrape script
    + Test Nichole's dataset in genderize
    + Analyze 2018 data
    + Draft intro
    + ~~Draft methods~~
    + ~~Outline results/discussion~~

1. Monthly journals report 
    + script 2 report figures

1. Estimated JIF 
    + ~~script JIF calculations~~

1. ASM blog post
    + Revise ergot post - Thurs

1. DEI certificate
    + Identify DEI person to interview
    + ~~"Barriers to Communicating" - Tues @ noon~~
    
1. Geographical survey - Mia

1. ~~Journal Club paper~~

1. ASM Staff Meeting - Wed @ 2pm

1. Suggestions for Begum - Thurs

#2018/10/30

**- Estimated JIF**

Wrote script to calculate the estimated JIF of each ASM journal. This required the 2018 citations of all items published in 2016 & 2017 that are indexed in WoS for each journal, as well as a list of the "citeable items" for each journal (document types: Article, Review & Proceedings paper). The calculation & script was pretty simple, the hardest part is getting the data. I can manually download with with two different searches (one for all citations & one for citable items), but WoS only allows downloads of 500 items at a time, so it takes a while to get all of the 1000's of records downloaded.

Saved a `csv` of today's estimate & sent it to Pat. Need to look at the APIs again now that I have an idea of what data I need & the search criteria to find it.

UM has access to Web Services Lite and Article Match Retrieval APIs. Looks like I should be able to:
1. use Web Services Lite to generate the list of all articles published by specified journals in a specified time frame.
Neither of the services returns citations by year. 
2. use a second search to generate a list of "citeable items". 
The problem is then figuring out how many cites they have... AMR only returns total cites, not a breakdown by year but it also returns a URL of the list of citing articles in Web of Science Core Collection. 
3. Use a script to identify those articles listed in the URL of citing articles & restrict to those published in the most recent year. That should work?

**- DEI certificate**

Attended "Barriers to Communicating" workshop. - Anti-Racism

Notes:
Instructor: Patricia Coleman-Burns

Workshop on teaching racisim to primarily white

Think about DEI in terms of ideas, as well as skin color, geography, gender, etc.

Think about "sex" terms vs "gender" terms (male/female vs man/woman)

Think about my color, understand some of where I come from. Don't erase what I am.

My job as a mentor is to tap into what you as a scholar bring to the table.

Sometimes the science needs to change. -- Who do you "norm" the data on? Who are you deciding is too costly to "save"?

How will my discipline be better b/c I do DEI research

It's about community, the "beloved community"

Challenging & changing your disciplines (canons)

Education to govern

What do you need to do this kind of work? What resources to be successful.

"Pyramid of Hate"

Concepts:
  + Retention & progession
      + address systemic biases
      + mentoring
  + Scholarly Interests
  + "Activism" or "Not"
  
Reflection: 

Prior to this workshop, I had considered that most changes within an organization are made sustainable by the incoming/younger generations. In that context, it seems obvious that the people best suited to initiate change are those who are actively participating and who can create a culture that recruits those who value those changes. What I found most compelling about this workshop was the shift from DEI in academia as a structure, to DEI in and throughout research. How can we design and approach our research question in a way that contributes to DEI in the research OUTCOMES. Not just the research community. I felt like that was really powerful and wish we had been able to spend more time learning tools and/or discussing how to identify those opportunities in non-obvious research projects.

**- Authorship paper**

Supposed to start drafting introduction but I'm considering changing my whole approach, splitting into three manuscripts:
    1. Who submits, publishes, and are the gatekeepers at ASM journals - breakdown of authors/editors/reviewers looking at all demographics: predicted gender, geographic/institutional location, etc
    2. Is there gender bias in peer review at ASM journals - models associating gender with editor/review outcomes, duration in peer review, etc
    3. Is there geographic bias in peer review at ASM journals - models associating geographic location/institution with review outcomes, etc.
    
Drafted outline & started methods for paper #1. Drafted rough outline of paper #2.

Continued analyzing genderize breakdown of results by country. Should we generate a modified probability with a higher cut off? (Edwards, 2018)

**- Lit review** XXXX

Edwards, 2018. "Gender differences in authorship are not associated with publication bias in an evolutionary journal"

Potvin, 2018. "Diversity begets diversity: A global perspective on gender equality in scientific society leadership"

#2018/10/29
**- Lab meeting**

**- Journal club paper** XX

**- Authorship paper** 

Finished drafting methods.

Started analyzing 2018 data, focusing on outcomes from Genderize.io

**- Lit review** XX

Read paper - Sieverding, 2018 - "Mother's work less" 

**- Weekly overview** X

Plan for week: Check in with fall goals & events this week. Layout items for each day

Send weekly report to Pat.

#Goals: October 22 - 26
1. Authorship paper:
    + Work on bugs in webscrape script
    + Test Nichole's dataset in genderize
    + Analyze 2018 data
    + Draft intro/methods

1. Monthly journals report - nothing

1. Estimated JIF - nothing

1. ASM blog post
    + ~~Suggestions to J Brubaker's post~~
    + ~~Revise ergot post~~
    + ~~Submit post~~

1. DEI certificate
    + Identify DEI person to interview
    
1. Geographical survey - Mia

1. ~~Journal Club~~

1. ~~ASM Journal Staff Meeting - Wed @ 1pm~~

1. ~~NCBI Command Line workshop - Thurs @ 1pm~~

#2018/10/25

**- NCBI Command Line workshop**

Notes: https://ftp.ncbi.nlm.nih.gov/pub/education/Mod_Workshops/2018/UMich_Oct/Commandline_Access/

Entrez API: eutils.ncbi.nlm.nih.gov/entrex/eutils

Entrez Direct (E-direct): command line version of E-Utilities - requires unix & Perl

epost/elink/esearch return the results of a search query into a history that can then be piped to efetch to retreive

**einfo:** Provides information about the available databases, Database names, Indexed fields, Links to other databases, Produces XML (or text output with –fields, -links provides info about each of the search databases in an XML format

**elink:** Returns related records  in the same (-related) or different (-target) database , Use link name from einfo to get the most precise results (-name linkname), Pipe into efetch, Use with –cmd neighbor to get a table of linked identifiers (elink XML

**esearch:** Uses standard web Entrez queries, Try searches on web interface first, Results stored in web environment, Pipe output to efetch, elink

**eFetch:** Produces full XML records for many databases and summaries 
(docsums) for all databases, Specialized formats for PubMed, sequence databases, Gene and others, In many cases the docsum contains enough information (efetch -format docsum == esummary), Parsing values from full XML can be more challenging than parsing the summarie - docsum returns XML format 

**xtract:** full-features XML parser that produces a tab deliminted output including selected items & conditional execution (flexible output formats) - use to parse any valid xml structure

+ `-pattern ` places the data from individual records into separate rows.
+ `-element` extracts values from specified fields into separate columns.
+ `-group`, `-block`, and `-subset` limit element exploration to selected XML subregions.
+ `-sep` specifies the character separating multiple fields in an ‘-element’ argument
    + Default is the tab character “\t” 
    + Example `-sep` “,” 
+ `-tab` specifies the character separating multiple values of an ‘-element’ argument
    + Default is a newline “\n”
+ Place `-sep` and `-tab` before `-element`
+ `-head` Creates output table header
    + Example: -sep ‘Organism\tNucAccessions\tAssemblyAccessions’
    + Place -head immediately after xtract command, before any exploration option

`efetch -db pubmed -id [numerical pmid] -format docsum | xtract -pattern DocumentSummary - element ID,Source,Title` Pull the data for a specific article in pubmed using the PMID, then select just the ID, source & title

```{r, eval=FALSE}
esearch -db pubmed -query 'antibiotic resistance[MeSH] AND metagenomic' | #search that returns into a search history (gives a count of results)
efetch - format docsum | #returns xml records
xtract -pattern DocumentSummary -sep "|" -element Id,Source,Title | #sep changes from the default of tab - pull text from xml structure
head -5
```
`esearch -db pubmed -query 'gender AND authorship'|efetch -format docsum|xtract -pattern DocumentSummary -sep "\n" -element Name|sort-uniq-count-rank|head -15` Count how many times authors appear on papers in the returned results

**- Seminar**

**- Authorship Paper**

Work on writing methods.

Need to analyze 2018 data - start with descriptive stats of gender (e.g., editors known vs unknown vs corrected, breakdown of known vs unknown by country).

**- Lit review**

Read 2 papers.

#2018/10/24

**- Lab meeting**

**- ASM blog post**

Generated google doc w. images & submitted to Julie on Slack.

**- Lit review**

Finished organizing current list of papers & the list of follow up papers. Read 2 papers.

#2018/10/23

**- Lit review**

Read a few papers, also tried to find a better way to organize my papers. Decide to compile all of them into a single `Rmd` file, which enables searchability & organization. 

**- Software Carpentry**

Monthly meeting @ 9am.

**- ASM blog post**

Revise ergot post based on Begum's suggestions. 

#2018/10/22

**- Lab Meeting**

Present journal club.

**- Journal club**

Finish prepping for lab meeting.

**- Lab Lunch**

**- ASM blog post**

Make suggestions to J. Brubaker's post.

**- Newsletter**

Edit newsletter proofs.

#Goals: October 15 - 19
1. Authorship paper:
    + ~~Finish hardcode editor genders - Email unknown names to Pat w. journal~~
    + Work on bugs in webscrape script
    + Test Nichole's dataset in genderize

1. Monthly journals report: 
    + ~~pull fresh usage/citation stats~~
    + ~~script 4 figures~~

1. Estimated JIF - nothing

1. ASM blog post
    + ~~Finish ergot post~~

1. DEI certificate
    + Identify DEI person to interview
    
1. Geographical survey - Mia
    + ~~get data to Mia to analyze!!~~

#2018/10/18

**- Journal Club**

Picked a paper for journal club next week. 

**- BA paper**

Went over & returned proofs for the petrobactin & sporulation paper. 

**- Thursday seminar**

**- Monthly journals report**

Finished the script to make all data fit across all variables. Successfully sourced six different scripts. There are two that need further development, then I need to move on to the more complicated stats & usage/citation stats.

#2018/10/17

**- Lab Meeting**

**- Authorship paper**

Ran final clean up to generate `csv` files for Mia. I will just have to change the last two editor genders (if at all), later.

**- Newsletter**

Edited draft of retreat write up.

**- ASM blog post**

Finished first draft (minus the conclusion) & sent it to Begum & Jesus for feedback. 

**- Our STEM**

Culled papers from email alerts.

#2018/10/16

**- ASM blog post**

Continued working on drafting the ergot post - added images, citations, and about 350 words.

**- Monthly journals report**

Finished cleaning up data for report-type analyisis & saved as a `csv` file. Started tweaking the analysis scripts to use the new dataset. Trying to write a function `test_list` to make all dataframes contain the same variables (e.g., journal or editor name) regardless of whether or not they have a variable value in that particular test. I'm stuck on getting `arrange` to recognize a column w/o specifically naming it. When that happens, I'll have 3 scripts completed.

#2018/10/15

**- Monthly journals report**

Pulled fresh usage & citation stats. Updated code for new datasets.

**- Authorship Paper**

Verified that all of the randomized group values were joined correctly.

Double checked names & genders from Mia's `csv` files. Seems that something weird happened when I generated the initial "unknown" list that mis-matched some names/institutions. Corrected those & sent two names to Pat to ask about. Also worked on the `verify_gender` script to correct mis-coded editors. Just waiting for the two other editors before we can move forward!

#Goals: October 8 - 12
1. Authorship paper:
    + ~~Hardcode editor genders - Mia working on new data~~
    + Test Nichole's dataset in genderize
    + ~~Finish pipeline with 2018 data~~

1. Monthly journals report: 
    + script 2 figures

1. Estimated JIF
    + ~~manually pull JIF data~~

1. ASM blog post
    + ~~make suggestions to Janet's post~~
    + ~~500 words to ergot post~~
    
1. Software carpentries workshop
    + ~~contribute to the lessons~~
    
1. ~~Follow up JCM & AEM editor requests~~

1. DEI certificate
    + ~~"Inclusive leadership" - Tuesday @ noon~~
    
1. Geographical survey - Mia
    + ~~gave editor names to Mia to check~~
    
#2018/10/11

**- Nick's Practice Talk**

**- Monthly Journals Report**

Have to figure out how to pull usage & citation stats more easily than Impact Vizor in order to automate the report. 

**- Estimated JIF**

Pulled from the web of science with the following search criteria:
  + SO=(Molecular "AND" CELLULAR BIOLOGY OR MICROBIOLOGY "AND" MOLECULAR BIOLOGY REVIEWS OR JOURNAL OF MICROBIOLOGY "AND" BIOLOGY EDUCATION OR MICROBIOLOGY SPECTRUM OR MICROBIOLOGY RESOURCE ANNOUNCEMENTS OR ECOSAL PLUS OR GENOME ANNOUNCEMENTS OR INFECTION "AND" IMMUNITY OR APPLIED "AND" ENVIRONMENTAL MICROBIOLOGY OR CLINICAL MICROBIOLOGY REVIEWS OR CLINICAL "AND" VACCINE IMMUNOLOGY OR MBIO OR JOURNAL OF BACTERIOLOGY OR JOURNAL OF VIROLOGY OR JOURNAL OF CLINICAL MICROBIOLOGY OR mSystems OR mSphere) AND PY=(2016 OR 2017) 
  + A citation report was generated and the data downloaded into excel files, 500 at a time  

Might need to pull all ASM publications from Impact Vizor, so I can determine the type of manuscripts & thus whether their citations "count" or not.

**- Authorship paper**

Finished writing a script to randomize manuscript numbers & link them into a grouped, randomized manuscript number. Also wrote code to assign randomized person.ids. 

Completed a workflow to clean & deidentify all of the data to get it ready for analysis. Only potentially identifying things left are the person's institutions & dates of submission/reciept/publication. The next step is to finish assigning gender to the editors & then we're done & ready to analyze!! (though I am running a script to verify that all of the randomized manu numbers were matched into single grouped random manu numbers). 

#2018/10/10

**- Authorship paper**

Mia kept working on adding names to the unknown editors list.

I worked on finishing up the workflow to try to anonymize the data. 

**- Our STEM**

Begum gave me the idea to start a weekly digest similar to Bik's microbiome digest, but centered around bias and diversity in STEM fields, academia, & journals. This morning I set up an email address with several RSS & ToC subscriptions. I plan to host the site from Github, though I have to decide whether or not to buy a domain name.

#2018/10/09

**- JCM & AEM Follow up**

Emailed papers with citation data to EiCs of JCM & AEM per their request at Microbe.

**- DEI certificate (Inclusive leadership)**

Traits of inclusive leader - the 6 C's:
  + Commitment - willing to invest time/energy/resources
  + Courage
      + be vulnerable
      + brave enough to distract harm
  + Cognizance of Bias
      + recognize their own biases 
      + realize the biases can narrow their field of vision
  + Curiosity 
      + open minded, 
      + seek other perspectives, 
      + always learning/innovating, 
      + active listener
      + important to remember that some people need time to process before responding
  + Cultural Intelligence 
      + confident & effective in cross cultural interactions  
      + seeks opportunities to experience & create culturally diverse environments
      + also need to be aware that your experiences may have been wrong/don't fit in a setting
  + Collaboration
      + seek TRUE collaboration
      + empowers individuals
      + diversity will make the end result of complex problems better, but it will NOT be faster

Practices of inclusive leader:
  + Set the stage for an inclusive environment - Universal Design
      + Representation (WHAT) - provide multiple means of representation to address the WHAT of learning (various ways to learn/acquire info)
      + Action & Expression (HOW) - provide multiple means of action & expression to support the HOW of learning
      + Engagement (WHY) - multiple means of engagement to answer the WHY of learning
  + Begin by establishing community/trust
      + survey in advance for intentional design of group activities
      + start with ice breakers and/or introductions
      + allow participants to identify their preferred names & pronunciation
      + gender pronouns on name tags
      + share your workshop discussion guidelines
      + be incremental 
      + community guidelines
      + share personal stories
  + Model inclusive behaviors
      + 
  + Liberating structures
      + "easy-to-learn microstructures that enhance relational coordination and trust. they quidkly foster lively participation in groups of any size, making it possible to truly include & unleash everyone"
      + in other words... timed, flexible facilitation techniques that maximize inclusion and can be easily adapted
      + liberating structures are a set of practices that make it possible for everyone to have a voice & for everyone to engage & seize opportunities
      + ALL voices matter!

Why it matters:
  + FYI: there are systemic & structural barriers to inclusive leadership

Resources:
  + lynda.com
  + coursera.org - all courses free for all students now!
  + Center for Positive Organizations - UM Ross (research on diversity & outcomes)
  + umich organizational learning
  + Inclusive leadership programs:
      + Inclusive excellence leadership Academy

**- ASM blog post**

Wrote 500 words of the ergot post.

#2018/10/08

**- Authorship paper**

Looked at output from latest run of the webscraping batch script. I don't know what to with it. I ended up with 6 more entries than I started with and several (more than 6) results are duplicated.

**- Lab meeting**

Read paper for journal club

**- editor requests**

Got updated data from Impact vizor.

**- SWC**

Github issue/pull request. https://github.com/datacarpentry/r-socialsci/pull/86

**- ASM blog post**

Make suggestions/edits to Janet's post.

#Goals: October 1 - 5
1. Authorship paper:
    + ~~check batch outputs~~
    + Hardcode editor genders - Mia working on new data
    + ~~Finish script to pull author names from URLs~~
    + Test Nichole's dataset in genderize
    + ~~get editor names ready for Mia to check~~

1. Monthly journals report: 
    + script 2 figures

1. ASM blog post
    + ~~make suggestions to Monika's post~~
    + ~~research/outline ergot post~~
    
1. Software carpentries workshop
    + contribute to the lessons
    + ~~work through R for Social Scientist lessons~~
    + ~~demo~~
    
1. Follow up JCM & AEM editor requests

1. DEI certificate
    + ~~clarify what counts toward the 5 "leadership" track workshops~~
    + ~~IDI survey~~
    + ~~"Change it up" - Thursday~~
    
1. Geographical survey - Mia
    + ~~Meeting 12:30pm - 4pm~~ - gave editor names to Mia to check

#2018/10/05

**- DEI workshop**

Submitted my reflection form for the bystander intervention training.

#2018/10/04

**- DEI workshop**

"Change it up""  - Bystander Intervention

notes:
  + think about a time when you were a witness of harm - happened/feel/intervene or not? why?
  + it isn't always easy, some "harm" occurs in spaces that are difficult to intervene in or where intervening may cause more harm
  + what is our role? what is my goal?
  + intervention methods provide the tools/skills for you to decide based on the context
  + bystander can even be when someone tells you about an event, not just witnessing
  + this is a lot like parenting?
  
blueprint
  + Notice a problem
      + identities impact what you notice
      + what do I think about alot? (every interaction is a reminder of how you don't fit)
      + what I don't think about 
      + "Sometimes you're a caterpillar" - youtube video
      + not pushing into areas where we're unsafe, but perhaps uncomfortable
      + "entitlement"
  + Assume responsiblity
      + motivation - what would motivate you to change it up?
      + structure the practice: choose a "harm" that you often notice, make a plan & follow through
  + Think it through
      + physical & emotional safety - how will identities impact the situation? are there others around to support you? what power dynamics are at play?
      + effectiveness - are people going to listen to what you have to say?
  + change it up!
  
Toolkit
  + Direct - confront the situation right away
  + Distract - create a diversion to interrupt the situation
  + Delegate - tell someone else (friend, prof, coworker) & decide together how to intervene
  + Delay - Check in later wtih those who were involved

**- Authorship paper**

I think I actually have a working webscraping script. I created a lot of conditionals to allow the different functions to be more flexible. Submitted as a batch script.

**- ASM blog post**

Finish research & outlining the ergot post.

#2018/10/03

**- ASM blog post**

Worked on research & outline for the ergot post.

**- Authorship paper**

Webscraping script errored out part way through b/c it tried to add "http://" to a link that already had "https://". Fixed that but then realized in some cases, pubmed stores the doi  in a wierd location. I ran the script anyway, but I'll probably have to fix it to run those that error out.

Less than 100 URLs succesfully ran, I figured out one problem (passing the journal name to the `some_journals` function), but not all pubmed entries have a doi (e.g., https://www.ncbi.nlm.nih.gov/pubmed/9396779), so I have to figure out a back up for that.

**- Misc**

Booked flight to DC.

#2018/10/02

**- Misc**

Worked on booking flight to DC for EiC meeting.

**- Authorship paper**

Finished the script to scrape author names from the URLs & submitted as a batch script. Fingers crossed!

Doing it within a `mutate` wasn't working, so I had to create a new tibble & `cbind` to the original dataset.

**- SWC**

Working through the first part of the R lessons for the demo later. 

Demo - 

**- DEI Certificate**

Emailed to ask about IDI survey & workshop choice. Signed up for additional workshops.

2018/10/01

**- Lab meeting**

Skimmed through Josh's materials for journal club. 

**- Authorship post**

Looks like the genderize script didn't run all of the names again. Probably run through it by hand. 
    + inspection reveals that of the 105,697 names run through genderize, only 44,370 are assigned genders.  
    + 85,751 unique name/country entries are run through with countries, but 57,896 are not assigned a gender
    + 21,314 are run through without country data, 4,716 don't recieve a gender (seems reasonable)
    + 42,862 names are above the threshold of 65% confidence
    + pull editors & group by gender, print for Mia to work on

Manuscript linking script completed & saved. 
    + looking at the num_matches document, 1,809 manuscripts don't have a matching grouped manuscript number?
    + Submit the script to fix the group manuscript numbers & see if that helps
    
Worked on webscraping authors from Nicole's dataset. Need to finish up the `get_author_function` b/c the `case_when` statement isn't working. Ryan suggested using the `x %in% y return(blah_y) x %in% z return(blah_z)` within an `sapply` function.

Succesfully mapped the function & pulled author's names!! Need to build in a `tryCatch` or something similar for when it doesn't work & will definitely need to submit as a batch script b/c it takes forever.

Following step is tidying the names & genders to match.

**- ASM blog post**

Made suggestions to Monika's post