---
title: "Lab Notebook: June 2018"
output: html_notebook
---
#Goals: June 25 - 29
1. EiC stats
    + Editor data for JCM & AEM - scale up to all journals?
    + Top competitors for all journals
  
1. Coursera Stats: 
    + Inferential Stats wk 4

1. XML parse: 
    + Scale up to AEM XML files on flux
    + figure out automating genderize.io - subscription?
  
1. Estimated IF
    + Emailed Tyler about WoS API - waiting for Clarviate response
    
1. Monthly journals report - got parameters from Melissa
    + Identify graphs/plots
    + Identify data needed

1. ASM blog post
    + first draft of Microbial Myths

#2018/06/28

**- Lab meeting**

**- XML parse**

Finally figured out why my script keeps failing when I scale up. Missing values in the creation of `manu_data` cause it to fail. Need to figure out how to replace missing values with a `Null` or `n/a` value. 

Next problem `"by" can't contain join column "person.id" which is missing from RHS`

**- ASM blog post**

Wrote second section of Microbial Myths - on aeseptic technique. One to go.

Also, came up with new blog series: "Stepping from the shadows: fore-women of microbiology". The concept is women in Pasteur & Koch's labs that developed the techniques that they get credit for.

#2018/06/27

**- WoS API**

Email response to Tyler with example. Oddly, when I repeated the data pull, it included citations from the most recent years so I asked if it were possible with an API.

**- genderize.io**

Send subscription info to Pat. Work on automating looping through country codes.

Problems:
  + Some country codes aren't in the list - download list of included country codes in JSON file, parse & join with `iso_code` to get rid of those that aren't included prior to join with database
  + Have to get rid of periods? - Done
  + Some country codes return an error (below), need to build into function to skip or suppress errors
```
No encoding supplied: defaulting to UTF-8. !!!! http returned status code:
502 !!!! message: Server error: (502) Bad Gateway
```

**- XML parse**

Meet with Nick to learn how to submit a batch file to parse 500 AEM XML files.

  1. Using a text editor, create a `.pbs` file in the home directory of the project (use parse_500_AEM as template)

  2. Fill in appropriate information (e.g., job name, email address, when you want email notifications, what resources you need)
  
  3. Save file and ensure that you have the appropriate modules (e.g., R) loaded
  
  4. Submit job: qsub title_of_batch_file.pbs
  
  5. Output will be the job number, which you can use to check the status:
      + check if started: qstat -t job#
      + check all jobs under unique name: qstat -u akhagan
      + cancel a job: qdel job#
      + check what a job is doing: qpeek job#

Possible to create a job dependent on the outcome of the previous job. 

Need to [set R module](http://arc-ts.umich.edu/software/default-modules/) to automatically load when I log on to flux. - DONE

Resources: 
  + Submitting pbs: http://arc-ts.umich.edu/flux/using-flux/pbs-basics/
  + Interactive jobs: http://arc-ts.umich.edu/document/interactive-pbs-jobs/
  
Screwed up by editing the same file in both flux & my local hard drive & copied the gender data back up into my flux `akhagan` folder for a back up in case I have to replace the repo sometime. Need to finish by moving `data` into `gender_data_backup`.

Ran another `pbs` job, this time with the command to `print` the first 6 `xml_top_list` so I can see what the file paths are and trouble shoot. 

**- ASM blog post**

Started the aseptic technique section of Microbial Myths. Wrote some, did more digging for research papers & emailed Jeff Karr at CHOMA to see what he could find on the origins of aseptic technique & confirmatory papers.

#2018/06/26

**- genderize.io**

Found a package that interfaces with genderize.io given a vector of names and a single country code. I'll have to loop through each list of names by country codes.

Also found a list of country codes to join with list of country names generated by the individuals address. 

**- XML parse**

Figured out how to load and use R on flux. Manually ran functions to randomly select & parse 50 XML files. Tested link_XML but didn't work very well since none of the randomly selected had relevant manuscripts included in the subset. Rerun with larger batch - for which I will have to run a batch script.

**- ASM blog post**

Write first section of Microbial Myths post (about sanitizing sponges). Two more to go.

**- Coursera: Inferential Stats wk4**

**- ASM all staff debrief from Microbe**

#2018/06/25

**- work on organization system + summer strategic goals**

**- Lab lunch**

**- Seminar**

**- Submit weekly report**

**- Publishing in Developing Countries Opinion**

Create survey asking researchers about their experiences in publishing. 

Find Umich Global Reach contacts to spread survey to other researchers.

#Goals: June 18 - 22
1. EiC stats
    + Editor data for JCM & AEM - scale up to all journals?
    + Top competitors for all journals
  
1. Coursera Stats: 
    + Inferential Stats wk 4

1. XML parse: 
    + ~~next step is scale up to all AEM XML files - need to randomly select & move 50, 100 files~~
    + ~~Or learn to use R on flux & have it randomly select 50 files~~
    + figure out genderize.io
  
1. Estimated IF
    + ~~Email Tyler about WoS API~~
    
1. ~~Endorsement letter for Marc~~

1. ~~Pick Journal Club Paper~~

1. Monthly journals report
    + Identify graphs/plots
    + Identify data needed
  
1. Publishing in Devloping countries Opinion Piece
    + ~~Email Ethiopian researchers~~
    + outline

#2018/06/21

**- Work on Journal Club presentation**

#2018/06/20

**- Finish Marc's Endorsement letter**

**- Work on Journal Club Presentation**

**- Email organized wishlist to Melissa**

**- Work on R script to randomly select & parse 50 XML files**

Still need to change directory in the script to the flux folder.

**- Finish script for editor data**

There's an issue with how R on Windows encodes files. In order to get my script to fully work I'll have to run it on a linux or Mac system. However, I was able to trouble shoot the rest of the script, including that function (using a different search/replacement characters).

Tried installing R & R studio to run on Ubuntu, but ran into a problem with R studio. It needs `addarmor` in order to run & I wasn't able to get `addarmor` to enable (even though its already supposed to be??)

Marc gave me instructions on how to run an R script on flux: 
```
1. Module load R/3.4.4

2. Module available R - lets me know what versions are available to load

3. start R

4. install.packages() -> set to home directory

5. Rscript <code/myfile.R>
```

Running a PBS job on flux: http://arc-ts.umich.edu/flux/using-flux/pbs-basics/

Submitting an interactive job on flux: http://arc-ts.umich.edu/document/interactive-pbs-jobs/

R studio for Linux: https://www.rstudio.com/products/rstudio/download-server/

apt-get commands: https://codeburst.io/a-beginners-guide-to-using-apt-get-commands-in-linux-ubuntu-d5f102a56fc4

#2018/06/19

**- Work on Marc's Endorsement letter**

**- Email Abel about publishing experience**

**- Email Tyler about WoS API**

Seems to be out of town until Thursday

**- Script for editor data**
Have a script that can generate a list of the ASM journals then generate CSV files containing all of the articles accepted & published by each editor (along with months published & doi)

Just need to figure out how to deal with the special characters in Editor names... Seems to be a version/software issue. Pat & others on Mac(?) can get it to work but I can't.

#2018/06/18

**- Marc's Rec letter**

**- organize wishlist**

**- Work on script to tidy data from ASM_subs report**

**- ASM Journals debrief**

#Goals: June 11 - 15
1. ASM blog post 
    + ~~incorporate edits from group to fungi survey post~~
    + ~~outline education blog post~~
    + ~~outline blog post follow up to Microbial Myths~~

1. Publishing in Devloping countries Opinion Piece
    + interview more researchers
    + outline

1. Coursera Stats: 
    + Inferential Stats wk 4
    + Start modeling

1. XML parse: 
    + next step is scale up to all AEM XML files - need to randomly select & move 50, 100 fles
    + Or learn to use R on flux & have it randomly select 50 files
    + figure out genderize.io

1. EiC stats
    + Editor data for JCM & AEM - scale up to all journals?
    + Top competitors for all journals

1. Pick Journal Club Paper

1. Monthly journals report
    + Identify graphs/plots
    + Identify data needed
    + API vs continual access to XML
  
1. ~~_Bacillus_ manuscript - submit to mBio - Thursday @ 11am~~
    
1. Estimated IF
    + Waiting for WoS API update from Pat
    + Figure out WoS API
    
1. Endorsement letter for Marc


#2018/06/14

**- Submit manuscript to mBio @11**

**- Meet with Pat @1:30**

Pat suggested "wire framing" a report - i.e. mock up with fake data to know what data we need from where.

Scott Martin (main campus) - ask Tyler Nix about getting the citations data for calculating IF. 

What I focus on depends on what I want to do: 
  + Research? - gender study
  + Journals data analysis - reports
  
Things I can do now:
  + wire frame the report
  + mSystems/AEM/JCM questions
  + check in with Tyler about the WoS api & cites

Notes on Flux:  
Tmucks - a way to run things in the background (have a sesssion that you can shut computer down & will still run)

PBS - job handler system - interactive mode (qsub-I)

$R -e "source(`file.R); command(..)"

$Rscript file.R

**- Lab meeting**

#2018/06/13

**- Outline Education blog post**

**- Outline Microbial Myths post**

**- Marc's rec letter**

**- PDA meeting at 12:15**

**- Travis' defense at 1:00**

#2018/06/12

**- Takeaways/feedback re: ASM**

- POM symbol idea: road signs

- Poster Talks:
    + multiple instruction emails with conflicting information for "speakers"
    + The selection for poster talks is currently opt-out, which means that people are being given poster talks with out explicit consent. While they recieve multiple emails telling them this is the case, it may be confusing if the initial email doesn't describe the selection system as opt-out (which it currently doesn't). Membership describes it as easier to deal with poster talk no-shows than switch to an opt-in only selection system, but this is problematic for attendees. There could be very negative impacts for the reputation and careers of presenters who don't show to poster talks or come unprepared because they didn't realize until the last minute that they were slated to give a talk. I think the selection method should be made more explicit from the beginning, if not changed altogether.  
    + the organisation of posters into sessions was confusing to attendees b/c it appeared as one item on their app agendas & printouts. A solution might be to add a note instructing attendees to click for poster numbers or embed the range of poster numbers on the session description.

- Track Hubs:
    + Entire days events on track hub screen between events
    + Airport style "you are here" maps
    + More extensive orientations & walkthroughs (e.g., it's extremely important to know where the first aid station is)
    + Extra floater during lunch to cover bathroom breaks

**- Revise fungi survey blog post**

**- Pull request to lab website**

**- List of requests/questions for journals analyisis**

1. Design new monthly report (need parameters from Melissa)
1. Identify high citation publishers to target for marketing
1. mBio transfer data from Maisha
1. mSystems rejection data (AEM + all journals?)
1. Impact by country of origin (AEM) - requires XML scrape
1. List of articles by editor, including citations and months since published (JCM & AEM)
1. Communicate with eJP about continual access
1. Communicate with eJP about author self-reports for gender/race/etc
1. Time to first decision
1. Time to publishing
1. Correlate reviewer decisions to citations
1. Identify areas missing good cited papers - look at competing journals on WoS by keywords
1. Correlation between number of revisions and citations


#2018/06/11

**- Bacillus manuscript**

Got edits back from Phil. Plan to submit on Thursday. 

**- Read NIH bias preprint**

http://www.sciencemag.org/news/2018/05/applicant-s-race-or-gender-don-t-appear-influence-nih-peer-reviewers

http://science.sciencemag.org/content/333/6045/1015

http://drugmonkey.scientopia.org/2018/05/29/nih-ginther-fail-a-transformative-research-project/

**- Update strategic plan**
    
#Goals: June 4 - 8
1. ASM blog post
    + incorporate edits from group to fungi survey post

1. Coursera Stats: Inferential Stats wk 4

1. XML parse - next step is scale up to all AEM XML files, waiting until after ASM

1. ~~ASM Transfer articles~~
    + ~~Practice talk on Monday~~
    + ~~Present on Thursday!!~~
    
1. _Bacillus_ manuscript - ~~Phil's edits (after Microbe)~~
    
1. Estimated IF
    + Waiting for WoS API update from Pat
    + Figure out WoS API
    
1. ~~Moderate Microbial Myths~~

#2018/06/10

- Maisha said that Arturo wants to compete with with Cell: Host & Microbe. Strategy is to find highly cited authors in CH&M & others (e.g. Nature Micro, eLIFE, PNAS, J infect diseases, etc. - look at list with updated impact factor) to contact specifically for marketing. How can I web-scrape & collate this data.


#2018/06/08

**- AEM Editors Meeting**

Suggestions

#2018/06/07

**- Journals Board Meeting Presentation**

  + Follow up with mSystems re: rejection data. 

  + Follow up with Maisha about mBio transfer data. 

**- AEM**

Harold wants to know the impact by country of origin (# citations per country normalized to the # papers published by that country). That data is in the XML files but doesn't seem to be carried into Impact Vizor. 

#2018/06/06

**- JCM Meeting**

JCM is interested in editor specific statistics: "For each editor, a list of papers they edited during 2015-2016, with the number of times each was cited? Let me know if it's too cumbersome or otherwise problematic"

**- Meet with Melissa**

Email dates for August meeting!

Talk about revamping the montly report. EJP reports are tricky b/c the documentations & parameter options aren't great. Currently Melissa does the reports for all journals except mBio manually. Some of the reports are multijournals, others have to be done on a per journal basis. On the whole it is pretty tedious. The mBio report is done by Maisha with some different stats. Melissa is going to note the parameters she uses.

Stats needed:
  + submissions
  + personal work loads (e.g., editor / EiC level stats)
  + acceptance rates
  + problem manuscripts (those that have been sitting in pergatory for a while, generally with the author)
  + citations reporting (e.g. like those I've included in the rejected article tracker)
  + other stats to help monitor editors, journal trends, themes, trend data, etc. - see mBio for ideas/template
  + Useage stats (from highwire, which pulls from scopus)
  
Starter task is to pick one journal to do a sample report on & circulate to the EiCs then refine based on input. Probably start with Impact Vizor data & highwire reports to decide layout, etc then work backwards to the long term plan, which maybe to pull XML files continuously from eJP to update data. 

#2018/06/04

**- Practice ASM talk again**

**- Coursera Stats: Inferential Stats wk 4**

**- ASM blog post edits**