---
title: "Summer 2018 Strategic Plan"
author: "Ada Hagan"
date: "July - September 2018"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

**Goals:** 
Specific, Measurable, Attractive, Realistic, Time-framed


#Writing/Research Goals

1. Gender Authorship survey paper
    i) parse/compile data from all XML files
    i) get data from genderize.io & merge
    i) research intro
    i) outline 
    i) analyze data
    i) generate first draft
        A) Intro
        B) Methods
        C) Results
        D) Discussion
    i) feedback from Schloss labbies
    i) generate second draft
    i) feedback from Pat
2. ASM Journals Report
    i) Identify graphs/plots
    i) Identify data needed
    i) Mock report for feedback
    i) Work with eJP for access
    i) generate scripts for each figure
    i) compile scripts into pipeline
3. Three blog posts for ASM
    i) PI & non-academic career blog post
        A) draft
        B) feedback from ?
        C) revise
        D) submit to Julie
        E) revise
    i) Microbial Myths blog post
        A) draft
        B) feedback from ?
        C) revise
        D) submit to Julie
        E) revise
    i) Pathogenic Fungi survey
        A) draft
        B) feedback from Jesus
        C) revise
        D) submit to Julie
        E) revise
4. BA perspective
    i) Outline
5. Estimated JIF
    i) Find R script for WoS API
    i) Write script to pull info for dois
    i) Test on 10 dois
    i) Script to identify included dois
      
###Looking ahead to next Strategic Plan (Oct - Dec)
1. Coursera courses
    i) Linear Regression & Modeling
    i) Bayesian Statistics
    i) Getting and Cleaning Data
    i) Exploratory Data Analysis
    i) Developing Data Products
2. Journey through publishing
    i) outline
    i) intro
    i) methods
    i) results
    i) discussion
    i) first revisions
    i) comments from ?
    i) revise
    i) draft to Pat
3. Publishing in developing countries perspective
    i) outline
    i) compile consensus data
    i) generate first draft
    i) feedback from Schloss labbies
    i) generate second draft
    i) feed back from Pat
    i) generate third draft
    i) submit
4. Submit BA perspective
    i) Draft
    i) First revision
    i) Revise draft
    i) Send draft to Phil
    i) Incorporate Phil's feedback
    i) Draft v3
    i) Make final changes
    i) Double check references
    i) Submit to ?    

#Personal Goals
1. Exercise: 6x/wk (Yoga - Sun/Tues/Fri, Walk - Mon/Wed/Thurs)
2. Clean and purge spare room
    i) clean & purge closet
    i) clean & purge dresser
    i) dispose of purged items
    i) clean carpets
3. Physical therapy: 6x/wk

#Strategic Plan
|Date | Distractions | Writing/Research Goals | Personal/Other Goals|
|:---:|:-------------------------------|:-------------------------------------------|:------------------------------------|
|7/2|Mom in town(M-T); Vacation(W-Sun)|||
|||||
|7/9|Zack & Hayley's Wedding (F-Sun)|finish myths post; genderize API script; XML scale up; find WoS API script||
|||||
|7/16||revise/submit myths post; outline/research authorship; complete XML scale up; list graphs for report|clean & purge desk|
|||||
|7/23|Chalk talk (R); MI Beerfest (F)|outline/research authorship; complete genderize scale up & merge; list data needed for report|clean & purge dresser|
|||||
|7/30||research/outline fungi post; draft authorship intro; analyze authorship; ejp access|clean & purge closet|
|||||
|8/6||draft fungi post; draft authorship methods; analyze authorship; report mockup|dispose of purge stuff|
|||||
|8/13||finish/revise fungi post; analyze authorship; report mockup||
|||||
|8/20|Code Review (R)|fungi post to Jesus; draft authorship results; report mockup; script to pull dois||
|||||
|8/27|Dax's birthday (M)|submit/revise fungi post; draft authorship discussion; report mockup; test WoS on 10 dois||
|||||
|9/3|Labor Day (M); Dept Picnic (F)|draft mentorship post; revise authorship; report mockup||
|||||
|9/10||finish/revise mentorship; authorship survey to?; script to identify JIF dois; report mockup||
|||||
|9/17|Research talk (R)|mentorship post to?; Revise/submit authorship survey to Pat; report mockup; research/outline BA perspective||
|||||
|9/24||submit/revise mentorship post; submit report mockup; research/outline BA perspective|Clean carpets|
|||||
